# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 359d5c2e70b6625f03f5d20077cb9c12640150e72a85faa6183ad65d2b8b22c69b9be1e69095e3a82ab23289cb1ceff16404ea1bc675326b6a8c3c6b4066257b

test:
  secret_key_base: 93376508eaca92a0cc2ee5cc070679c7db09e413a65c884ddbb3e4061970d0e0dba56fb20d3309a2e385b05513378964ad488595ababff8e642d290b95b362e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
